vich_uploader:
    db_driver: orm

    mappings:
        events:
            uri_prefix: /images/events
            upload_destination: '%kernel.project_dir%/public/images/events'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
