vich_uploader:
    db_driver: orm

    mappings:
        event:
            uri_prefix: /images/event
            upload_destination: '%kernel.project_dir%/public/images/event'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
